Update sync-branches-through-pr-2.yaml

diff --git a/.github/workflows/sync-branches-through-pr-2.yaml b/.github/workflows/sync-branches-through-pr-2.yaml
--- a/.github/workflows/sync-branches-through-pr-2.yaml
+++ b/.github/workflows/sync-branches-through-pr-2.yaml
@@ -55,17 +55,17 @@ jobs:
           fi
         done
 
-        # Handle the Makefile manually
-        # Handle the Makefile manually
+        # Handle the Makefile in case there are other canges apart KF_TAG value
         MAKEFILE="components/odh-notebook-controller/Makefile"
         if [[ -f "$MAKEFILE" && "$(git status --porcelain=v1 2>/dev/null | grep -c "$MAKEFILE")" -gt 0 ]]; then
           echo "Resolving conflicts in $MAKEFILE while preserving KF_TAG."
 
-          # Extract the KF_TAG line from the target branch
-          KF_TAG_TARGET=$(git show :2:"$MAKEFILE" | grep '^KF_TAG \?=')
+          # Extract KF_TAG from the target branch
+          KF_TAG_TARGET=$(cat "$MAKEFILE" | grep -oP '^KF_TAG\s*=\s*\K.*' || echo "hhhhhhh")
+
           if [[ -z "$KF_TAG_TARGET" ]]; then
-            echo "KF_TAG not found in target branch. Exiting with an error."
-            exit 1
+            echo "KF_TAG not found in target branch; using a fallback value."
+            KF_TAG_TARGET="KF_TAG ?= main"
           fi
 
           # Process the conflicting Makefile
@@ -79,15 +79,13 @@ jobs:
             { print $0 }                           # Print other lines
           ' "$MAKEFILE" > "$MAKEFILE.new"
 
-          # Replace the original Makefile with the resolved version
+          # Replace original Makefile with resolved version
           mv "$MAKEFILE.new" "$MAKEFILE"
           echo "Preserved KF_TAG as: $KF_TAG_TARGET"
 
           # Stage the resolved Makefile
           git add "$MAKEFILE"
         fi
-
-
 
         # Commit the merge changes
         git commit -m "Merge ${SOURCE_BRANCH} into ${TARGET_BRANCH} with resolved conflicts, preserving KF_TAG in Makefile" || echo "Nothing to commit"
@@ -98,6 +96,7 @@ jobs:
         git checkout -b $SYNC_BRANCH
         git push origin $SYNC_BRANCH
         echo "branch=$SYNC_BRANCH" >> $GITHUB_OUTPUT
+
 
     - name: Create a Pull Request
       env:
